#!/bin/bash
# AUTHOR:			BJ Veurink
# NAME: 			Youtubed (youtube dee) deamon
# LICENSE:		GNU GPLv3
[[ $XDG_SESSION_TYPE == "x11" ]] && clipboard="xclip -o"
[[ $XDG_SESSION_TYPE == "wayland" ]] && clipboard="wl-paste"
options=${options:-"--no-playlist"}
format=${format:-"ba"}
output=${output:-"%(title)s.%(ext)s"}
expire_notify=${expire_notify:-5000}
echo "waiting for link"
while true; do
	next=`$clipboard 2>/dev/null`
	if [[ $next != $prev ]]; then
		prev=$next
		if [[ $next =~ ^(https?\:\/\/)?((www\.|music\.)?youtube\.com|youtu\.be)\/.+$ ]]; then
			title=$(yt-dlp --get-title $next )
			notify-send -t ${expire_notify} "yt-dlp: ${title}"
			yt-dlp --format $format $options -o $output $next
			echo "waiting for link"	
		fi
	fi
	sleep 30
done
